DECLARE
V_NOMBRE VARCHAR2(30);
V_SALARIO NUMBER(8);
V_EMAIL VARCHAR2(50);
V_INICIO DATE;
V_TERMINO DATE;
V_CODIGO_ERROR NUMBER(8);
V_MSJ_ERROR VARCHAR2(250);
E_ERROR_ANTIGUEDAD EXCEPTION;
V_FECHA_ANTI NUMBER(2);
V_FECHA_CONTRATO DATE;
BEGIN
RAISE_APPLICATION_ERROR(-20777,'MI PRIMER RAISE APP ERROR');--  -20000 HASTA -20999
    BEGIN
        SELECT HIRE_DATE INTO V_FECHA_CONTRATO FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
        V_FECHA_ANTI:= TRUNC(MONTHS_BETWEEN(SYSDATE,V_FECHA_CONTRATO)/12);
        IF V_FECHA_ANTI<=18 THEN
            RAISE E_ERROR_ANTIGUEDAD;
        END IF;
    EXCEPTION
        WHEN E_ERROR_ANTIGUEDAD THEN
            DBMS_OUTPUT.PUT_LINE('EMPLEAD NO CUMPLE CON ANTIGUEDAD LABORAL');
    END;
    BEGIN
        SELECT START_DATE, END_DATE INTO V_INICIO, V_TERMINO FROM JOB_HISTORY WHERE EMPLOYEE_ID=101;
    EXCEPTION
        WHEN OTHERS THEN
            V_CODIGO_ERROR:=SQLCODE;
            V_MSJ_ERROR:=SQLERRM;
            INSERT INTO ERRORES_BLOQUE_PLSQL
            (ID_SECUENCIA, COD_ERROR, MSJ_ERROR, CURSOR_PLSQL, DATO_EXTRA)
            VALUES(SEQ_ERROR_PLSQL.NEXTVAL, V_CODIGO_ERROR, V_MSJ_ERROR,'SELECT START_DATE, END_DATE','EMPLEADO 101');
    END;
    DBMS_OUTPUT.PUT_LINE(1);
    DBMS_OUTPUT.PUT_LINE(2);
    BEGIN
        SELECT EMAIL INTO V_EMAIL FROM EMPLOYEES WHERE DEPARTMENT_ID=50;
    EXCEPTION
         WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('LA SENTENCIA INTO PARA EMAIL SE CAE POR MUCHAS FILAS');
    END;
    
    BEGIN
        SELECT FIRST_NAME INTO V_NOMBRE FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES: '||V_NOMBRE);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('LA SENTENCIA INTO PARA NOMBRE SE CAE');
            V_NOMBRE:='SIN NOMBRE';
            DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_NOMBRE);
    END;
    
    DBMS_OUTPUT.PUT_LINE(3);
    SELECT SALARY INTO V_SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
    DBMS_OUTPUT.PUT_LINE('EL SALARIO ES: '||V_SALARIO);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('LA SENTENCIA EN EL BLOQUE DE EJECUCIÓN NO DEVUELVE FILA');
END;

/

DECLARE
CURSOR C_EMP(PID_DEPTO NUMBER DEFAULT 50) IS
    SELECT LAST_NAME, FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID=PID_DEPTO;
V_LAST_NAME VARCHAR2(50);
V_FIRST_NAME VARCHAR2(50);
V_SALARY NUMBER(9);
V_HIRE_DATE DATE;
BEGIN
   /* OPEN C_EMP;
    LOOP
        FETCH C_EMP INTO V_LAST_NAME,V_FIRST_NAME,V_SALARY,V_HIRE_DATE;
        EXIT WHEN C_EMP%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_LAST_NAME||' '||V_FIRST_NAME||' '||V_SALARY||' '||V_HIRE_DATE);
    END LOOP;
    CLOSE C_EMP;
*/

    FOR R_EMP IN C_EMP() LOOP
        DBMS_OUTPUT.PUT_LINE(R_EMP.LAST_NAME||' '||R_EMP.FIRST_NAME||' '||R_EMP.SALARY||' '||R_EMP.HIRE_DATE);
    END LOOP;
END;